Added and re-organized JSON items
derhuerst/flightradar24-client pull request #18
Opened 2018-02-28 11:13 UTC by E3V3A

- added ESTIMATED radar type (disabled)
- added missing JSON items: squawk,climb,timestamp,glider,ground
- renamed `modeSCode` to `modes` to match lower-case use of other items
- changed order of items to match JSON
- added placeholders for: maxage, stats, ems

2018-02-28 11:13 UTC, E3V3A commented
This would fix #14.

2018-02-28 18:50 UTC, derhuerst commented
Note: This PR contains many changes. In the future, please take the time to split your proposals into individual PRs, so people can discuss them separately.

> - renamed `modeSCode` to `modes` to match lower-case use of other items

Please keep it as `modeSCode`, for two reasons:

- the other items use [camelCase](https://en.wikipedia.org/wiki/Camel_case)
- don't mix breaking changes with other proposals in one PR

> - changed order of items to match JSON

What does this mean?

> - added placeholders for: maxage, stats, ems

No placeholders please. Only add code that actually does things.

2018-02-28 18:57 UTC, derhuerst requested changes

2018-02-28 18:57 UTC, derhuerst commented on lib/radar.js
> +	FAA:   		true, 	// use US/Canada radar data source
Make the key [camel-cased](https://en.wikipedia.org/wiki/Camel_case). Same for `FLARM`, `MLAT`, `ADSB`, `ESTIMATED`.

2018-02-28 18:57 UTC, derhuerst commented on lib/radar.js
> +	// stats: 	true, 	//
Remove unused code.

2018-02-28 18:57 UTC, derhuerst commented on lib/radar.js
> +		faa: opt.FAA ? '1' : '0',				//
Remove unnecessary slashes. Keep the diff as small as possible.

2018-02-28 18:57 UTC, derhuerst commented on lib/radar.js
> +	return fetch(url, {mode: 'cors', redirect: 'follow', headers})
There is a reason why this is in place. Keep it as before and propose changes in another PR.

2018-02-28 18:57 UTC, derhuerst commented on lib/radar.js
> +				squawk: d[6],				// Mode-3/A Transponder code: 4-digit [octal] is the "Squawk" ATC assigned code
Use `squawkCode` [as discussed](https://github.com/derhuerst/flightradar24-client/issues/14#issuecomment-363597195).

2018-02-28 18:57 UTC, derhuerst commented on lib/radar.js
> +				ground: d[14],				// Airplane is "onGround": [0|1]
Use `isOnGround`.

2018-02-28 18:57 UTC, derhuerst commented on lib/radar.js
> +				climb: d[15],				// "Rate of Climb" (RoC) is a vertical speed [ft/m]
Use `rateOfClimb`.

2018-02-28 18:57 UTC, derhuerst commented on lib/radar.js
> +				glider: d[17],				// Aircraft is a glider:   [0|1]  (There are usually no or very few gliders registered on earth!)
Use `isGlider`.

2018-02-28 18:58 UTC, derhuerst commented
Also, please update the tests and the readme.

2018-03-05 09:24 UTC, E3V3A commented
Hi Jannis!

Your proposed changes, essentially reverts my entire PR. In addition, with my very limited (and recently acquired) nodejs skills, I don't think I qualify to update the tests. So since my PR was primarily intended to provide you with the missing details, feel free to implement it at your own convenience. I will not be able to make any further changes.

Best Regards,
E:V:A

2018-03-05 10:45 UTC, derhuerst commented
Hey,

note that my proposed changes only revert the part that is out of scope of this PR. I'm willing to accept it as long as it doesn't change this that we discussed before *not to be changed*.

> So since my PR was primarily intended to provide you with the missing details [...]

Thanks again! Thanks to your input in #14, people can now make `flightradar24-client` a more comprehensive tool.

> I will not be able to make any further changes.

Hm, sad to hear that. Would you continue doing this if I updated the tests? (You would still have to implement my proposed changes though.)

2018-03-08 19:52 UTC, closed without merging